config/routes.rb
WizzSecurity::Application.routes.draw do
  resources :visitors
  match 'users/:id/supbanned' => 'users#supbanned', :as => :supbanned
  match 'admins/:id/supuser' => 'admins#supuser', :as => :supuser
  match 'admins/:id/delbanned' => 'admins#delbanned', :as => :delbanned
  resources :admins do
    put "searchdate", :on=>:member
    put "searchplate", :on=>:member
    put "addresbanned", :on=>:member
  end

  resources :users do
    put "addbanned" , :on=>:member
    put "search", :on=>:member
    put "searchplate", :on=>:member
    put "searchdoc", :on=>:member
    put "searchname", :on=>:member
    get "supbanned", :on=> :member
  end
 
  resources :agents do
    put "setrecord", :on=>:member
    put "setout",:on=>:member
  end

  resources :residentials

end

app/views/admins/_apendnewuser.html.haml
-usr=@user
%tr{:id=>"item_#{usr.id}"}
  %td=usr.address
  %td=usr.telephone
  %td=usr.name
  %td=usr.habitants_number
  %td=usr.user_status.name
  %td
    = link_to "Editar", edit_user_path(usr), :class => 'btn btn-mini'
    

app/views/admins/_appendresbanned.html.haml
-t=@viss
%tr{:id=>"item_#{t.id}"}
  %td= link_to t.name, visitor_path(t)
  %td= t.identification
  %td= t.visitor_status.name
  %td= link_to "Eliminar",delbanned_url(:residential_id=>@admin.residential.id,:visitor_id=>t.id),:class => 'btn btn-danger',:remote=>true,:onclick=>"$('#item_#{t.id}').remove();"

app/views/admins/_form.html.haml
= form_for @admin, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :user_name, :class => 'control-label'
    .controls
      = f.text_field :user_name, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.text_field :password, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :residential_id, :class => 'control-label'
    .controls
      = f.number_field :residential_id, :class => 'number_field'
  .control-group
    = f.label :admin_status_id, :class => 'control-label'
    .controls
      = f.number_field :admin_status_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admins_path, :class => 'btn'

app/views/admins/_setresult.html.haml
- @records.order("entrance DESC").each do |t|
  %tr
    %td= link_to t.visitor.name, visitor_path(t.visitor)
    %td= t.visitor.identification
    %td= t.plate_number
    %td= t.entrance
    %td= t.exit
    %td= t.visitor.visitor_status.name

app/views/admins/addresbanned.js.haml
alert('Persona satisfactoriamente agregada a la lista');
$('#newResidentialBannedVisitorModal').modal('hide');
$('#bannedList_table tbody').append("#{escape_javascript(render :partial=>'appendresbanned')}");

app/views/admins/edit.html.haml
- model_class = @admin.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/admins/index.html.haml
- model_class = Admin.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:user_name)
      %th= model_class.human_attribute_name(:password)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:residential_id)
      %th= model_class.human_attribute_name(:admin_status_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @admins.each do |admin|
      %tr
        %td= link_to admin.id, admin_path(admin)
        %td= admin.name
        %td= admin.user_name
        %td= admin.password
        %td= admin.description
        %td= admin.residential_id
        %td= admin.admin_status_id
        %td=l admin.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_path(admin), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_path(admin), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_path, :class => 'btn btn-primary'

app/views/admins/new.html.haml
- model_class = @admin.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/admins/searchdate.js.haml
$('#dateSearchModal').modal('hide');
$('#visitorsTable tbody').empty()
$('#visitorsTable tbody').append("#{escape_javascript(render :partial=>'setresult')}");

app/views/admins/searchplate.js.haml
$('#plateSearchModal').modal('hide');
$('#visitorsTable tbody').empty()
$('#visitorsTable tbody').append("#{escape_javascript(render :partial=>'setresult')}");

app/views/admins/show.html.haml
- model_class = @admin.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @admin.name
%p
  %strong= model_class.human_attribute_name(:user_name) + ':'
  %br
  = @admin.user_name
%p
  %strong= model_class.human_attribute_name(:password) + ':'
  %br
  = @admin.password
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @admin.description
%p
  %strong= model_class.human_attribute_name(:residential_id) + ':'
  %br
  = @admin.residential_id
%p
  %strong= model_class.human_attribute_name(:admin_status_id) + ':'
  %br
  = @admin.admin_status_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admins_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_path(@admin), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_path(@admin), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/admins/supuser.js.haml
alert('Direccion Eliminada!!!')