config/routes.rb
WizzSecurity::Application.routes.draw do
  resources :visitors
  match 'users/:id/supbanned' => 'users#supbanned', :as => :supbanned
  match 'admins/:id/supuser' => 'admins#supuser', :as => :supuser
  match 'admins/:id/delbanned' => 'admins#delbanned', :as => :delbanned
  resources :admins do
    put "searchdate", :on=>:member
    put "searchplate", :on=>:member
    put "addresbanned", :on=>:member
  end

  resources :users do
    put "addbanned" , :on=>:member
    put "search", :on=>:member
    put "searchplate", :on=>:member
    put "searchdoc", :on=>:member
    put "searchname", :on=>:member
    get "supbanned", :on=> :member
  end
 
  resources :agents do
    put "setrecord", :on=>:member
    put "setout",:on=>:member
  end

  resources :residentials

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  belongs_to :visitor_status
  has_many :records
  has_many :users, :through => :records
  has_many :user_banned_lists
  has_many :residential_banned_lists;
  has_many :residentials, :through => :records
  has_many :banned_by_users, :through => :user_banned_lists, :source => :user
  has_many :banned_by_residentials, :through => :residential_banned_lists, :source => :residential
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visitors }
    end
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
    @visitor = Visitor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visitor }
    end
  end

  # GET /visitors/new
  # GET /visitors/new.json
  def new
    @visitor = Visitor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visitor }
    end
  end

  # GET /visitors/1/edit
  def edit
    @visitor = Visitor.find(params[:id])
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(params[:visitor])

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render json: @visitor, status: :created, location: @visitor }
      else
        format.html { render action: "new" }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visitors/1
  # PUT /visitors/1.json
  def update
    @visitor = Visitor.find(params[:id])

    respond_to do |format|
      if @visitor.update_attributes(params[:visitor])
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor = Visitor.find(params[:id])
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.haml
= form_for @visitor, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :identification, :class => 'control-label'
    .controls
      = f.text_field :identification, :class => 'text_field'
  .control-group
    = f.label :idpictureurl, :class => 'control-label'
    .controls
      = f.text_field :idpictureurl, :class => 'text_field'
  .control-group
    = f.label :residential_id, :class => 'control-label'
    .controls
      = f.number_field :residential_id, :class => 'number_field'
  .control-group
    = f.label :visitor_status_id, :class => 'control-label'
    .controls
      = f.number_field :visitor_status_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), visitors_path, :class => 'btn'

app/views/visitors/edit.html.haml
- model_class = @visitor.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/visitors/index.html.haml
- model_class = Visitor.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:identification)
      %th= model_class.human_attribute_name(:idpictureurl)
      %th= model_class.human_attribute_name(:residential_id)
      %th= model_class.human_attribute_name(:visitor_status_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @visitors.each do |visitor|
      %tr
        %td= link_to visitor.id, visitor_path(visitor)
        %td= visitor.name
        %td= visitor.identification
        %td= visitor.idpictureurl
        %td= visitor.residential_id
        %td= visitor.visitor_status_id
        %td=l visitor.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_visitor_path(visitor), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), visitor_path(visitor), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_visitor_path, :class => 'btn btn-primary'

app/views/visitors/new.html.haml
- model_class = @visitor.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/visitors/show.html.haml
- model_class = @visitor.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @visitor.name
%p
  %strong= model_class.human_attribute_name(:identification) + ':'
  %br
  = @visitor.identification
%p
  %strong= model_class.human_attribute_name(:idpictureurl) + ':'
  %br
  = @visitor.idpictureurl
%p
  %strong= model_class.human_attribute_name(:visitor_status_id) + ':'
  %br
  = @visitor.visitor_status_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), visitors_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_visitor_path(@visitor), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), visitor_path(@visitor), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'