config/routes.rb
WizzSecurity::Application.routes.draw do
  resources :visitors
  match 'users/:id/supbanned' => 'users#supbanned', :as => :supbanned
  match 'admins/:id/supuser' => 'admins#supuser', :as => :supuser
  match 'admins/:id/delbanned' => 'admins#delbanned', :as => :delbanned
  resources :admins do
    put "searchdate", :on=>:member
    put "searchplate", :on=>:member
    put "addresbanned", :on=>:member
  end

  resources :users do
    put "addbanned" , :on=>:member
    put "search", :on=>:member
    put "searchplate", :on=>:member
    put "searchdoc", :on=>:member
    put "searchname", :on=>:member
    get "supbanned", :on=> :member
  end
 
  resources :agents do
    put "setrecord", :on=>:member
    put "setout",:on=>:member
  end

  resources :residentials

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :residential
  belongs_to :user_status
  has_many :records
  has_many :user_banned_lists,:dependent => :destroy
  has_many :visitors, :through => :records
  has_many :banned_visitors, :through => :user_banned_lists, :source => :visitor
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html 
        format.js
      else
        format.html 
        format.js
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
  def addbanned
    @emptyarray=[]
    @user=User.find(params[:id])
    if (@vis=Visitor.where("name=:visitor_name",{:visitor_name=>params[:visitor][:name]})) != @emptyarray
      @viss=@vis[0]
      @user.banned_visitors<<@viss
    else
      @viss=Visitor.new(:name=>params[:visitor][:name],:visitor_status_id=>1)
      @viss.save
      @user.banned_visitors<<@viss
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  def supbanned
    @emptyarray=[]
    
    @entry=UserBannedList.where("user_id = :userid AND visitor_id = :visitorid",{:userid=>params[:user_id],:visitorid=>params[:visitor_id]})
    if @entry!=@emptyarray
      @item=params[:visitor_id]
      UserBannedList.destroy(@entry[0])
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  def search
    @emptyarray=[]
    @begindate=params[:begin]
    print "******************************************************"
    @start_date = DateTime.civil(params[:record][:"begin(1i)"].to_i,params[:record][:"begin(2i)"].to_i,params[:record][:"begin(3i)"].to_i,params[:record][:"begin(4i)"].to_i,params[:record][:"begin(5i)"].to_i)
    @end_date = DateTime.civil(params[:record][:"end(1i)"].to_i,params[:record][:"end(2i)"].to_i,params[:record][:"end(3i)"].to_i,params[:record][:"end(4i)"].to_i,params[:record][:"end(5i)"].to_i)

    @records=Record.where("user_id=:id AND entrance>=:start AND entrance<=:end ",{:start=>@start_date,:end=>@end_date,:id=>params[:id]}).order("entrance DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end
  def searchplate
    @records=Record.where("user_id=:id AND plate_number=:number",{:id=>params[:id],:number=>params[:record][:plate_number]})
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  def searchname
#     @records=Record.where("user_id=:id AND name=:number",{:id=>params[:id],:number=>params[:record][:name]})
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def searchdoc
#     @records=Record.where("user_id=:id AND plate_number=:number",{:id=>params[:id],:number=>params[:record][:identification]})
    
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_apendnewuser.html.haml
-usr=@user
%tr{:id=>"item_#{usr.id}"}
  %td=usr.address
  %td=usr.telephone
  %td=usr.name
  %td=usr.habitants_number
  %td=usr.user_status.name
  %td
    = link_to "Editar", edit_user_path(usr), :class => 'btn btn-mini'
    

app/views/users/_apendvisitor.html.haml
-t=@viss
%tr{:id=>"item_#{t.id}"}
  %td= link_to t.name, visitor_path(t)
  %td= t.identification
  %td= t.visitor_status.name
  %td= link_to "Eliminar",supbanned_url(:user_id=>@user.id,:visitor_id=>t.id),:class => 'btn btn-danger',:remote=>true, :onclick=>"$('#item_#{t.id}').remove();"

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :address, :class => 'control-label'
    .controls
      = f.text_field :address, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.text_field :password, :class => 'text_field'
  .control-group
    = f.label :enabled, :class => 'control-label'
    .controls
      = f.number_field :enabled, :class => 'number_field'
  .control-group
    = f.label :telephone, :class => 'control-label'
    .controls
      = f.number_field :telephone, :class => 'number_field'
  .control-group
    = f.label :habitants_number, :class => 'control-label'
    .controls
      = f.number_field :habitants_number, :class => 'number_field'
  .control-group
    = f.label :residential_id, :class => 'control-label'
    .controls
      = f.number_field :residential_id, :class => 'number_field'
  .control-group
    = f.label :user_status_id, :class => 'control-label'
    .controls
      = f.number_field :user_status_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/_setresult.html.haml
- @records.order("entrance DESC").each do |rec|
  %tr{:id=>"item_#{rec.id}"}
    %td=link_to rec.visitor.name
    %td=rec.visitor.identification
    %td=rec.plate_number
    %td=rec.user.address
    %td=rec.entrance
    %td=rec.exit

app/views/users/addbanned.js.haml
alert('Persona satisfactoriamente agregada a la lista');
$('#newBannedVisitorModal').modal('hide');
$('#bannedList_table tbody').append("#{escape_javascript(render :partial=>'apendvisitor')}");

app/views/users/create.js.haml
$('#newUserModal').modal('hide');
$('#usersTable tbody').append("#{escape_javascript(render :partial=>'admins/apendnewuser')}");

app/views/users/edit.html.haml
- model_class = @user.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:address)
      %th= model_class.human_attribute_name(:password)
      %th= model_class.human_attribute_name(:enabled)
      %th= model_class.human_attribute_name(:telephone)
      %th= model_class.human_attribute_name(:habitants_number)
      %th= model_class.human_attribute_name(:residential_id)
      %th= model_class.human_attribute_name(:user_status_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.name
        %td= user.address
        %td= user.password
        %td= user.enabled
        %td= user.telephone
        %td= user.habitants_number
        %td= user.residential_id
        %td= user.user_status_id
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = @user.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/search.js.haml
$('#searchDateFormModal').modal('hide');
$('#visitorRecord_table tbody').empty()
$('#visitorRecord_table tbody').append("#{escape_javascript(render :partial=>'setresult')}");

app/views/users/searchplate.js.haml
$('#searchPlateFormModal').modal('hide');
$('#visitorRecord_table tbody').empty()
$('#visitorRecord_table tbody').append("#{escape_javascript(render :partial=>'setresult')}");

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Address:
  = @user.address
%p
  %b Password:
  = @user.password
%p
  %b Enabled:
  = @user.enabled
%p
  %b Telephone:
  = @user.telephone
%p
  %b Habitants number:
  = @user.habitants_number
%p
  %b Residential:
  = @user.residential_id
%p
  %b User status:
  = @user.user_status_id

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/users/supbanned.js.haml
alert("eliminado satisfactoriamente");