config/routes.rb
WizzSecurity::Application.routes.draw do
  resources :visitors
  match 'users/:id/supbanned' => 'users#supbanned', :as => :supbanned
  match 'admins/:id/supuser' => 'admins#supuser', :as => :supuser
  match 'admins/:id/delbanned' => 'admins#delbanned', :as => :delbanned
  resources :admins do
    put "searchdate", :on=>:member
    put "searchplate", :on=>:member
    put "addresbanned", :on=>:member
  end

  resources :users do
    put "addbanned" , :on=>:member
    put "search", :on=>:member
    put "searchplate", :on=>:member
    put "searchdoc", :on=>:member
    put "searchname", :on=>:member
    get "supbanned", :on=> :member
  end
 
  resources :agents do
    put "setrecord", :on=>:member
    put "setout",:on=>:member
  end

  resources :residentials

end

app/models/agent.rb
class Agent < ActiveRecord::Base
  belongs_to :residential
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  # GET /agents
  # GET /agents.json
  def index
    @agents = Agent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agents }
    end
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
    @agent = Agent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agent }
    end
  end

  # GET /agents/new
  # GET /agents/new.json
  def new
    @agent = Agent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agent }
    end
  end

  # GET /agents/1/edit
  def edit
    @agent = Agent.find(params[:id])
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(params[:agent])

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render json: @agent, status: :created, location: @agent }
      else
        format.html { render action: "new" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agents/1
  # PUT /agents/1.json
  def update
    @agent = Agent.find(params[:id])

    respond_to do |format|
      if @agent.update_attributes(params[:agent])
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent = Agent.find(params[:id])
    @agent.destroy

    respond_to do |format|
      format.html { redirect_to agents_url }
      format.json { head :ok }
    end
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/views/agents/_form.html.haml
= form_for @agent do |f|
  -if @agent.errors.any?
    #error_explanation
      %h2= "#{pluralize(@agent.errors.count, "error")} prohibited this agent from being saved:"
      %ul
        - @agent.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :residential_id
    = f.number_field :residential_id
  .actions
    = f.submit 'Save'

app/views/agents/_result.html.haml
-if @result==0
  %h1 El visitante NO puede ingresar!!! 
  %h6 La direccion a la que se dirije no existe.
-else
  -if @result==1
    %h1 El visitante NO puede ingresar!!!
    %h6 El residencial le ha restringido el acceso.
  -else 
    -if @result==2
      %h1 El visitante NO puede ingresar!!!
      %h6 La direccion a la que se dirije le ha restringido el acceso.
    -else
      -if @result==4
        %h1 El visitante ha marcado salida satisfactoriamente
        %h6 Salida = #{DateTime.now} (aa-mm-dd hh:mm)
      -else
        -if @result==5
          %h1 La salida no se marco.
          %h6 Hubo un problema al intentar marcar la salida, por favor verifique los datos ingresados.
        -else
          %h1 Puede ingresar sin ningun problema!!
          %h6 El visitante fue autorizado para poder ingresar al residencial.

app/views/agents/edit.html.haml
%h1 Editing agent

= render 'form'

= link_to 'Show', @agent
\|
= link_to 'Back', agents_path

app/views/agents/index.html.haml
%h1 Listing agents

%table
  %tr
    %th Name
    %th Password
    %th Description
    %th Residential
    %th
    %th
    %th

  - @agents.each do |agent|
    %tr
      %td= agent.name
      %td= agent.password
      %td= agent.description
      %td= agent.residential_id
      %td= link_to 'Show', agent
      %td= link_to 'Edit', edit_agent_path(agent)
      %td= link_to 'Destroy', agent, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Agent', new_agent_path

app/views/agents/new.html.haml
%h1 New agent

= render 'form'

= link_to 'Back', agents_path

app/views/agents/setout.js.haml
$('#visitors_identification').attr("value","");
$('#visitors_name').attr("value","");
$('#modalbody').empty();
$('#modalbody').append("#{escape_javascript(render :partial=>'result')}");
$('#ResultModal').modal('show')

app/views/agents/setrecord.js.haml
$('#visitor_name').attr("value","");
$('#visitor_identification').attr("value","");
$('#record_plate_number').attr("value","");
$('#user_address').attr("value","");
$('#modalbody').empty();
$('#modalbody').append("#{escape_javascript(render :partial=>'result')}");
$('#ResultModal').modal('show')

app/views/agents/show.html.haml
.container#content
  .content
    .row
      .span3
        .well
          %img{:src=>"/assets/31.png"}
      .span9
        %span.label.label-info
          %i.icon-user Nombre:
        %br
        =@agent.name
        %br
        %span.label.label-info
          %i.icon-tags Residencial
        %br
        =@agent.residential.name
        %br
        %span.label.label-info
          %i.icon-magnet Descripcion
        %br
        =@agent.description
        %br
  
%center
  %h1 Marcar Ingreso
  .well#insideform
    %p
      Ingrese los datos requeridos para marcar un ingreso. Debe llenar todos y cada uno de los datos requeridos. Si el solicitante no le puede dar todos los datos, NO se le permitira el acceso.
    
    =form_for @agent, :url => setrecord_agent_path,:html => { :method=>'put',:class => 'well.form-vertical' ,:remote=> true} do |f|
      .controls
        %p
          %span.label.label-important
            Nombre
        =text_field :visitor,:name
      .controls
        %p
          %span.label.label-important
            Doc. Identificacion:
        =text_field :visitor, :identification
      .controls
        %p
          %span.label.label-important
            Placas:
        =text_field :record, :plate_number
      .controls
        %p
          %span.label.label-important
            Direccion a la que se dirije
        =text_field :user,:address
      .form-actions
        = f.submit "Solicitar Ingreso", :class => 'btn btn-primary'
  
%center
  %h1 Marcar Salida
  .well
    %p
      Ingrese el numero del documentos de identificacion, es la UNICA manera de buscar al visitante. Si un visitante no posee un documento de idenficacion NO se le debe permitir el ingreso al residencial.
    =form_for @agent, :url => setout_agent_path,:html => { :method=>'put',:class => 'well.form-vertical' ,:remote=> true} do |f|
      .controls
        %p
          %span.label.label-success
            Nombre
        =text_field :visitors,:name
      .controls
        %p
          %span.label.label-success
            Doc. Identificacion:
        =text_field :visitors, :identification
      .form-actions
        = f.submit "Marcar Salida", :class => 'btn btn-primary'

        
%p#notice= notice


  
.modal.hide.fade#ResultModal
  .modal-header
    %button.close{"data-dismiss"=>"modal"}x
    %p#modalmessage
  .modal-body#modalbody
   